### ISSUE TITLE
Migrating our containers to GitHub Container Registry

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/governance#16]
We've discussed it in the past (see https://github.com/kedacore/keda/issues/995) but I think it's time to migrate our Docker images to GitHub Container Registry which brings our artifacts closer to our GitHub repos and gives us more insights on the adoption (# of pulls per tag, instead of vague total pull count).

We are dry-running this for our HTTP add-on and it's fairly straightforward.

Here is how people can discover them:
![image](https://user-images.githubusercontent.com/4345663/108207789-82155a00-7128-11eb-8579-da9b89d17bee.png)

Per Docker image, you can then see the pull count per tag:
![image](https://user-images.githubusercontent.com/4345663/108207847-922d3980-7128-11eb-94e9-4c5de33b5eca.png)

I've used this on other projects as well and it gives you a lot more insights than Docker Hub, and would never move back.

> ⚠ If we do this, then we should move all Docker images to our new registry for sake of completeness, but keep the old ones on Docker Hub.

**Comment by tomkerkhove** [comment]
Thoughts @kedacore/keda-maintainers?

**Comment by tomkerkhove** [comment]
Happy to pick this up.

**Comment by zroubalik** [comment]
Sounds good!

**Comment by tomkerkhove** [comment]
Thoughts on this @jeffhollan @anirudhgarg @ahmelsayed?

**Comment by tomkerkhove** [comment]
Yesterday we've agreed that this is the way forward, but we'll publish them in both Docker Hub & GitHub Container Registry until GHCR is out of preview.

We will:
- [ ] Automatically push Docker images to GitHub Container Registry ([#1650](https://github.com/kedacore/keda/issues/1650))
- [ ] Re-tag and push our existing images in Docker Hub to GitHub Container Registry (GHCR) ([#1651](https://github.com/kedacore/keda/issues/1651))
- [ ] Use Docker images from GitHub Container Registry ([#127](https://github.com/kedacore/charts/issues/127))
- [ ] Open a GitHub Discussion with context on why we are doing this and how it impacts people

([Meeting notes](https://hackmd.io/cEi_FerdQvyTvB1i-5U0kg?view#March-2nd-Meeting))

**Comment by tomkerkhove** [comment]
I'd propose to write a small blog post with this as well, next to the GitHub Discussion, what do you think?

**Comment by tomkerkhove** [comment]
Blog post is published on https://keda.sh/blog/migrating-to-github-container-registry/ and discussion is open on https://github.com/kedacore/keda/discussions/1700

**Comment by tomkerkhove** [comment]
GHCR is GA, it's time to remove Docker Hub support and close this deprecation.

Agreed @kedacore/keda-maintainers? Happy to pick this up.

**Comment by JorTurFer** [comment]
I agree

**Comment by zroubalik** [comment]
+1

**Comment by tomkerkhove** [comment]
KEDA v2.6 will only be available on GitHub Container Registry.
