### ISSUE TITLE
Propose to graduate to become a CNCF Incubation project

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/governance#2]
We've seen a healthy adoption of KEDA by the community over time and received various contributions for running KEDA, operating it, and providing more scalers.

In the next couple of weeks, we will open a proposal to graduate to a CNCF Incubation project as we believe that we are approaching this next level in our project timeline.

Graduation process: https://github.com/cncf/toc/blob/master/process/graduation_criteria.adoc#incubating-stage

### What we will do before opening the proposal
- [x] Provide branding guidelines for our logos (https://github.com/kedacore/keda/issues/1090)
- [x] Provide a thorough security policy (https://github.com/kedacore/governance/issues/3)
- [ ] Setting up full container & code scanning
  - [x] Setup container scanning on-push (https://github.com/kedacore/keda/issues/1040)
  - [ ] Setup container scanning for published images (https://github.com/kedacore/keda/issues/1041)
  - [ ] Setup security scanning for Helm charts (https://github.com/kedacore/charts/issues/64)
- [ ] Improve our coverage of CII Badge (https://github.com/kedacore/governance/issues/8)

### How can the community help?
- If you are an existing KEDA user, please let us know and get listed on keda.sh. ([docs](https://github.com/kedacore/keda#become-a-listed-keda-user))

**Comment by tomkerkhove** [comment]
Our proposal has been opened with CNCF TOC

**Comment by tomkerkhove** [comment]
Security policy is available on https://github.com/kedacore/keda/blob/main/SECURITY.md
