### ISSUE TITLE
Switch default branches from master to main

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/governance#39]
Switch default branches from master to main to be more inclusive.

## Things to keep in mind 💡

- Rename the branch instead of re-creating ([docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch))
- Verify branch policies are aligned
- Verify workflow triggers are aligned
- Verify external systems are updated (Snyk, Artifact Hub, etc)
- Verify scripts using the branch name

### Impact on contributors

Members will have to update their local environments (or forks).

```
git branch -m master <BRANCH>
git fetch origin
git branch -u origin/<BRANCH> <BRANCH>
git remote set-head origin -a
```

## Task List

- [x] https://github.com/kedacore/keda/issues/1092
- [x] https://github.com/kedacore/charts/issues/195
- [x] https://github.com/kedacore/keda-docs/issues/584
- [x] https://github.com/kedacore/external-scalers/issues/13
- [x] GitHub template
- [x] OLM Operator
- [x] HTTP add-on
- [x] External Scaler for Azure Cosmos DB
- [x] https://github.com/kedacore/keda-external-scaler-azure-durable-functions/issues/19
- [x] https://github.com/kedacore/external-scaler-samples/issues/2
- [x] Samples
- [x] Sample - RabbitMQ consumer and sender
- [x] Sample - .NET Core worker processing Azure Service Bus Queue scaled by KEDA
- [x] https://github.com/kedacore/sample-javascript-eventhub-azure-function/issues/6
- [x] https://github.com/kedacore/sample-python-kafka-azure-function/issues/5
- [x] https://github.com/kedacore/sample-go-storage-queue/issues/1
- [x] https://github.com/kedacore/sample-go-gcppubsub/issues/4
- [x] https://github.com/kedacore/sample-typescript-kafka-azure-function/issues/7
- [x] https://github.com/kedacore/sample-hello-world-azure-functions/issues/17
- [x] https://github.com/kedacore/sample-azure-functions-on-ocp4/issues/3

**Comment by JorTurFer** [comment]
All the repos are updated but chart and docs. I will update them other day with more focus and care

**Comment by tomkerkhove** [comment]
Thanks a ton for the monkey work @JorTurFer !

**Comment by tomkerkhove** [comment]
We're done here 🏆
