### ISSUE TITLE
Provide more mature roadmap

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/governance#48]
Provide more mature roadmap so we can better manage work and provide a better way of consuming the information for end-users to set expectations.

The new GitHub Projects will be used to bring our backlog to life.

### Tasks

- [x] Set up a new GitHub Project
- [x] Automatically add new core issues to our roadmap
- [ ] Document how work needs to be added to iterations
- [ ] Document how end-users can consume our backlog
  - [x] Update our GitHub repo
  - [ ] Update our docs

**Comment by tomkerkhove** [comment]
GitHub Project is available on https://github.com/orgs/kedacore/projects/2/views/1

**Comment by tomkerkhove** [comment]
Automatically add new core issues to our roadmap was done through  https://github.com/kedacore/keda/pull/2622
