### ISSUE TITLE
Community improvements for CloMonitor 

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/governance#49]
CloMonitor is a new tool by the CNCF to show the health of projects and provide tips and guidance on how to improve.

There are a few things that we should improve to align with the traditional approach of OSS communities.

Current results: https://clomonitor.io/projects/keda/keda

### Task list

- [x] Add Artifact Hub badge
- [x] Add FOSSA badge
- [x] Add `Adopters` file with link to our overview and how to be added
- [x] Add `Roadmap` file with link to our roadmap
  - Relates to https://github.com/kedacore/governance/issues/48
- [x] Add `Governance` file with link to our governance repo
- [x] Add `CODE_OF_CONDUCT` file
  - We already have it but needs to be pulled from our `.github` repo; see https://github.com/cncf/clomonitor/issues/68

Example: https://github.com/kubernetes/kubernetes/pull/108110

**Comment by tomkerkhove** [comment]
Only need to surface Code of Conduct which depends on https://github.com/cncf/clomonitor/issues/68

**Comment by tomkerkhove** [comment]
![image](https://user-images.githubusercontent.com/4345663/157078514-f273ad93-7bb2-4cff-891c-ecae85d8339a.png)
